spring:
  application:
    name: oauth
  redis:
    host: 192.168.1.201
    database: 1

server:
  port: 8890

eureka:
  client:
    service-url:
      defaultZone: http://admin:mosh123456@localhost:8760/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

